from modelo.Ataque import Ataque

ATAQUES_DISPONIBLES = [
    Ataque("Placaje", "normal", "fisico", 40),
    Ataque("Lanzallamas", "fuego", "especial", 90),
    Ataque("Ascuas", "fuego", "especial", 40),
    Ataque("Rayo", "electrico", "especial", 90),
    Ataque("Surf", "agua", "especial", 90),
    Ataque("Patada Baja", "lucha", "fisico", 85),
    Ataque("Mega Patada", "normal", "fisico", 120),
    Ataque("Hidrobomba", "agua", "especial", 110),
    Ataque("Llamarada", "electrico", "especial", 110),
    Ataque("Ventisca", "hielo", "especial", 110),
    Ataque("Bomba Huevo", "normal", "fisico", 100),
    Ataque("Terremoto", "tierra", "fisico", 100),
    Ataque("Martillazo", "agua", "fisico", 100),
    Ataque("Psiquico", "psiquico", "especial", 90),
    Ataque("Vuelo", "volador", "fisico", 90),
    Ataque("Patada Salto Alta", "lucha", "fisico", 130),
    Ataque("Ataque Aereo", "volador", "fisico", 140),
    Ataque("Cascada", "agua", "fisico", 80),
    Ataque("Picadura", "bicho", "fisico", 80),
    Ataque("Tijera-X", "bicho", "fisico", 80),
    Ataque("Roca Afilada", "roca", "fisico", 110),
    Ataque("Avalancha", "roca", "fisico", 80),
    Ataque("Joya de luz", "roca", "fisico", 110),
    Ataque("Puño Trueno", "electrico", "fisico", 75),
    Ataque("Puño Hielo", "hielo", "fisico", 75),
    Ataque("Puño Fuego", "fuego", "fisico", 75),
    Ataque("Bombardeo", "fuego", "fisico", 110),
    Ataque("Rayo Solar", "planta", "especial", 110),
    Ataque("Enfado", "dragon", "fisico", 110),
    Ataque("Cola dragon", "dragon", "fisico", 75),
    Ataque("Cometa Dragon", "dragon", "especial", 120),
    Ataque("Juego Sucio", "siniestro", "fisico", 110),
    Ataque("Triturar", "siniestro", "fisico", 80),
    Ataque("Mordisco", "siniestro", "fisico", 40),
    Ataque("Pulso Umbreo", "siniestro", "especial", 80),
    Ataque("Poltergeist", "fantasma", "fisico", 80),
    Ataque("Sombra Vil", "fantasma", "fisico", 60),
    Ataque("Bola Sombra", "fantasma", "especial", 90),
    Ataque("Hoja Afilada", "planta", "fisico", 70),
    Ataque("Rayo Burbuja", "agua", "especial", 65),
    Ataque("Burbuja", "agua", "especial", 40),
    Ataque("Latigo Cepa", "planta", "fisico", 40),
    Ataque("Rueda Fuego", "fuego","fisico", 50),
    Ataque("Polución", "veneno","especial", 30),
    Ataque("Acido", "veneno","especial", 50),
    Ataque("Colmillo veneno", "veneno","fisico", 50),
    Ataque("Amago", "normal","fisico", 30),
    Ataque("Destructor", "normal","fisico", 40)

]
